### ISSUE TITLE
Extension to 3D datasets

### ISSUE THREAD

**Issue by clementpoiret** [ImMrMa/SegCaps-pytorch#6]
Hello,

I'm working on a 3D dataset (MRI scans), and I'd like to try SegCaps. Do you think your implementation can be used for 3D segmentation ? 

Thank you,
Clément

**Comment by MikeManifold** [comment]
I think it maybe can't work well in 3D dataset.
I suggest u-net 3d or other latest models.
I don't think this model can have good performance than others above.

**Comment by clementpoiret** [comment]
I see, segcaps seemed to be promising in 2D, I'll continue my searches.
Thanks for your quick answer!
